# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [97]:
import numpy as np
import random

In [121]:
from sklearn import preprocessing as p
data = np.random.rand(4,7) * 20
normalized_data = p.normalize(data)
print(data)
print('\n')
print(normalized_data)

[[ 4.92419621  3.56889831  9.69411156  8.25018689  8.29277239 18.97362329
   2.03043013]
 [18.14784576 18.12020846  8.5884188  11.08916343  8.92923182  1.05607901
   5.70601871]
 [ 2.92389236 14.89490318 12.52262504  6.48038002 15.4580921   8.24382821
   7.03843119]
 [ 9.85541635  4.88764152  3.6081929  17.71939483 13.67900731  0.27002296
  14.60780937]]


[[0.19588684 0.14197245 0.38563631 0.32819631 0.32989038 0.75477964
  0.08077146]
 [0.58334753 0.58245915 0.27606764 0.35645201 0.28702279 0.03394679
  0.18341526]
 [0.10431358 0.53139463 0.44676059 0.23119581 0.55148711 0.29410907
  0.25110499]
 [0.33831861 0.16778389 0.12386273 0.60827476 0.46957557 0.0092694
  0.50145966]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [143]:
data = np.random.randint(10, size = (8,10))
print(data, '\n')
data[np.argmin(np.sum(data, axis=1))]

[[1 3 8 7 2 5 1 9 9 5]
 [2 3 8 9 5 4 9 8 8 9]
 [2 3 5 5 3 7 6 0 1 4]
 [1 2 6 2 1 9 8 8 5 0]
 [4 1 0 1 1 3 6 7 5 6]
 [0 2 5 9 7 7 6 2 6 7]
 [7 0 8 3 4 8 5 8 3 3]
 [5 2 5 3 1 9 6 7 9 5]] 



array([4, 1, 0, 1, 1, 3, 6, 7, 5, 6])

In [145]:
'''data = np.random.randint(10, size = (3,3))
print(data, '\n')
data[np.argmin(np.sum(data, axis=1))] ''' #проверка на маленькой матрице

[[1 9 8]
 [6 2 5]
 [5 5 6]] 



array([6, 2, 5])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [163]:
a = np.array([1,2,3,4])
b = np.array([33, 55, 66, 34])

np.linalg.norm(a - b)

93.28451104015072

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np


In [2]:
dfile = np.loadtxt('minutes_n_ingredients.csv', delimiter = ',', dtype = 'int32', skiprows = 1)
dfile[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [3]:
dfile1 = dfile[:, 1:] #массив без 1го столбца
srednelement = np.average(dfile1, 0)
print('среднее значение по столбцам:', srednelement)
maxelement = np.max(dfile1, 0)
print('максимальное значение по столбцам:', maxelement)
minelement = np.min(dfile1, 0)
print('минимальное значение по столбцам:', minelement)
medianelement = np.median(dfile1, 0)
print('медиана по столбцам:', medianelement)


среднее значение по столбцам: [2.16010017e+04 9.05528000e+00]
максимальное значение по столбцам: [2147483647         39]
минимальное значение по столбцам: [0 1]
медиана по столбцам: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [4]:
q = np.quantile(dfile[:,1], 0.75, axis = 0) #вычисленный квантиль
dfile3 = dfile[dfile[:, 1] <= q]
print('Количество строчек в новом массиве:',dfile3.shape[0])
print('Ограниченный значением квантиля массив:','\n',dfile3)


Количество строчек в новом массиве: 75461
Ограниченный значением квантиля массив: 
 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [5]:
dfile4 = dfile[dfile[:, 1] == 0]
print(dfile4.shape[0]) #количество рецептов, у которых указана продолжительность 0
dfile44 = np.copy(dfile) #копирование изначального массива
np.place(dfile44[:, 1], dfile44[:, 1] == 0, 1) #замена продолжительности со значением 0 на значение 1
dfile[410:413], dfile44[410:413] #мы видим изначальный массив со значением 0 и измененный массив уже со значением 1 

479


(array([[ 18800,    270,     17],
        [  9325,      0,     10],
        [422167,     45,      8]]),
 array([[ 18800,    270,     17],
        [  9325,      1,     10],
        [422167,     45,      8]]))

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [6]:
len(np.unique(dfile[:,0]))


100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [7]:
print('Различные значения кол-ва ингредиентов:', '\n', np.unique(dfile[:,2]))
print('Сколько различных значений присутсвует в рецептах:', len(np.unique(dfile[:,2])))

Различные значения кол-ва ингредиентов: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
Сколько различных значений присутсвует в рецептах: 37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [8]:
dfile7 = dfile[dfile[:, 2] <= 5]
print(dfile7, '\n\n', 'количество рецептов, состоящих не более чем из 5 ингридиентов', dfile7.shape[0])


[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]] 

 количество рецептов, состоящих не более чем из 5 ингридиентов 17262


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [9]:
dfile8 = dfile[:, 2] / dfile44[:, 1] #используется dfile44 из 4 заданаия, т.к там продолжительность равная 0 заменена на 1
print(dfile8[:,np.newaxis]) #массив из того, сколько в среднем ингридиентов приходится на одну минуту рецепта
print('Максимальное количество ингридиентов на одну минуту рецепта:',np.max(dfile8))


[[0.26666667]
 [0.28      ]
 [0.6       ]
 ...
 [0.23076923]
 [0.8       ]
 [0.1       ]]
Максимальное количество ингридиентов на одну минуту рецепта: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [10]:
dfile9 = np.copy(dfile)
dfile9 = np.sort(dfile9, axis = 0)[::-1][:100]
sredn_colvo = np.average(dfile9[:,2])
print('Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:',sredn_colvo)

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 28.22


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [11]:
import random

dfile[np.random.choice(len(dfile), size = 10, replace = False)] 


array([[291623,     40,     10],
       [366704,     47,     12],
       [217025,      6,      4],
       [445489,      5,      7],
       [ 30580,     60,      6],
       [430058,     15,     11],
       [ 36360,     34,      9],
       [418546,      5,      8],
       [ 33385,     20,      8],
       [445181,     80,      4]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [12]:
sredn_ingr = np.average(dfile[:,2]) #среднее количество ингридиентов в рецептах
vsego_recept = dfile.shape[0] #сколько всего рецептов
men_sredn = dfile[dfile[:, 2] < sredn_ingr].shape[0] # количство рецептов, в которых кол-во ингредиентов меньше среднего
print(f'Процент рецептов, кол-во ингредиентов в которых меньше среднего: ,{men_sredn/vsego_recept*100}%')


Процент рецептов, кол-во ингредиентов в которых меньше среднего: ,58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [13]:
s1 = (dfile[:,2] <= 5)[:,np.newaxis] 
s2 = (dfile[:,1] <= 20)[:,np.newaxis]
s4 = np.concatenate((s1, s2), axis=1)
s5 = np.sum(s4, axis = 1)[:,np.newaxis]
np.place(s5, s5[:, 0] == 1, 0)
np.place(s5, s5[:, 0] == 2, 1)
final_ar = np.concatenate((dfile, s5), axis=1)
print(final_ar)
print('Количество простых рецептов:', np.sum(final_ar[:,3]))

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]
Количество простых рецептов: 9552


13. Выведите процент "простых" рецептов в датасете

In [14]:
prost_recipe = np.sum(final_ar[:,3])
all_recipe = dfile.shape[0]
procent_recipe = prost_recipe / all_recipe * 100
print(f'Процент "простых" рецептов в датасете:, {procent_recipe}%')

Процент "простых" рецептов в датасете:, 9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [15]:
dfile14 = np.copy(dfile)
short_recipe = dfile14[dfile[:,1] < 10]
midle_recipe = dfile14[(10 <= dfile[:,1]) & (dfile[:,1] < 20)]
long_recipe = dfile14[dfile[:, 1] >= 20]
min_recipe = min(len(short_recipe), len(midle_recipe), len(long_recipe))
print(min_recipe)
itog_recipes = np.array([short_recipe[:min_recipe], midle_recipe[:min_recipe], long_recipe[:min_recipe]])
itog_recipes


7588


array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]])