# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:
arr = np.random.uniform(0, 20 , size = (4,7)) #метод для генерации случайных чисел из равномерного распределения
arr
normalizedarr = (arr-np.min(arr))/(np.max(arr)-np.min(arr))
normalizedarr

array([[0.23418192, 0.82415381, 0.30242984, 0.        , 0.78716716,
        0.80776246, 0.07895886],
       [0.11954698, 0.75874036, 0.56546342, 0.00943169, 0.78715627,
        0.09115695, 0.48474024],
       [1.        , 0.06440745, 0.5098276 , 0.09839312, 0.83603262,
        0.71753562, 0.53361959],
       [0.22473285, 0.37721561, 0.20287035, 0.93487195, 0.00431996,
        0.54615071, 0.7822793 ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
matrix = np.random.randint(0, 10, size = (8, 10))
print(matrix)
matrix[np.argmin(np.sum(matrix, axis = 1))]

[[2 4 0 6 8 7 2 1 4 2]
 [1 5 1 6 0 5 2 3 3 2]
 [3 6 8 0 5 4 4 0 2 9]
 [8 1 5 7 3 7 6 0 7 3]
 [3 3 9 2 4 0 0 3 7 8]
 [3 5 4 0 6 5 3 1 5 6]
 [2 5 8 8 1 2 8 2 4 7]
 [4 4 9 7 2 9 4 7 2 5]]


array([1, 5, 1, 6, 0, 5, 2, 3, 3, 2])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
a = np.array([1,2,3,4])
b = np.array([33, 55, 66, 34])

np.linalg.norm(a - b)

93.28451104015072

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [30]:
file = np.loadtxt('minutes_n_ingredients.csv',  delimiter = ',', dtype = 'int32', skiprows = 1)
file1 = file.copy()
file[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [31]:
file2 = file1[:, 1:]
minvalue = np.min(file2, axis = 0)
maxvalue = np.max(file2, axis = 0)
averagevalue = np.average(file2, axis = 0)
medianvalue = np.median(file2, axis = 0)
print('Минимальное значение по столбцам', minvalue)
print('Максимум по столбцам', maxvalue)
print('Среднее значение по столбцам', averagevalue)
print('Медиана по столбцам', medianvalue)

Минимальное значение по столбцам [0 1]
Максимум по столбцам [2147483647         39]
Среднее значение по столбцам [2.16010017e+04 9.05528000e+00]
Медиана по столбцам [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [32]:
q = np.quantile(file1[:,1], 0.75)
file3 = file1[file1[:,1]<=q]
file3

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [99]:
count = len(file[file[:,1] == 0])
print('Количество рецептов, для которых продолжительность равна 0:', count)
file4 = file.copy()
file4[file4[:, 1] == 0][:,1] = 1 
file[410:413], file4[410:413] #пример

Количество рецептов, для которых продолжительность равна 0: 479


(array([[ 18800,    270,     17],
        [  9325,      0,     10],
        [422167,     45,      8]]),
 array([[ 18800,    270,     17],
        [  9325,      0,     10],
        [422167,     45,      8]]))

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [45]:
print('количесвто уникальных рецептов:', len(np.unique(file[:, 0])))

количесвто уникальных рецептов: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [52]:
print('количесвто различных значений кол-ва ингредиентов:', len(np.unique(file[:, 2])))
np.unique(file[:, 2])

количесвто различных значений кол-ва ингредиентов: 37


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [54]:
file7 = file.copy()
file7[file7[:,2] <= 5]
print(file7, '\n\n', 'количество рецептов, состоящих не более чем из 5 ингридиентов', file7.shape[0])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993    140     14]] 

 количество рецептов, состоящих не более чем из 5 ингридиентов 100000


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [62]:
file8 = file4[:,2] / file4[:, 1]
print(file8[:, np.newaxis])
print('Максимальное количество ингридиентов на одну минуту рецепта:', np.max(file8))

[[0.26666667]
 [0.28      ]
 [0.6       ]
 ...
 [0.23076923]
 [0.8       ]
 [0.1       ]]
Максимальное количество ингридиентов на одну минуту рецепта: 23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [80]:
file9 = file1[file1[:,1].argsort()]
file9 = file9[:-101:-1]
file9
print('Cреднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью', np.average(file9[:, 2]))


Cреднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью 6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [87]:
import random
#file10= random.sample(file4, 10)
file4[[random.sample(range(len(file4)),10)]]

C:\Users\Admin\AppData\Local\Temp\ipykernel_3776\3954950190.py:3: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  file4[[random.sample(range(len(file4)),10)]]


array([[495316,    140,     28],
       [220969,     90,      7],
       [171294,     90,      6],
       [120504,     25,      9],
       [202193,     70,      8],
       [406985,    490,      4],
       [ 17199,    110,      9],
       [188259,    270,     21],
       [412659,     40,      7],
       [439600,     30,      8]])

In [88]:
#второй способ 
import random

file4[np.random.choice(len(file4), size = 10, replace = False)] 


array([[109591,     20,      3],
       [284138,     40,      6],
       [203414,     15,      8],
       [  2695,     45,      8],
       [302750,     10,      3],
       [229172,      5,      4],
       [232134,     45,     10],
       [ 86671,    128,      8],
       [344950,    490,     11],
       [160227,     45,     13]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [95]:
vsegorecipes = len(file)
averageznach = np.average(file4[:,2])
recipesmin = len(file4[file4[:, 2] < averageznach])
print(f'Процент рецептов, кол-во ингредиентов в которых меньше среднего: {round((recipesmin/vsegorecipes) * 100, 2)}%')

Процент рецептов, кол-во ингредиентов в которых меньше среднего: 58.99%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [132]:
file12 = file4.copy()
file12 = np.insert(file12, 3, 0, axis = 1)
print(file13)
a = (file12[:,1] <= 20) & (file12[:,2] <= 5)
file12[:,3][a] = 1
file12[100:200]

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


array([[261088,     80,     16,      0],
       [ 66257,    125,      8,      0],
       [404093,     11,      8,      0],
       [208241,     25,     10,      0],
       [491998,     40,     13,      0],
       [ 43341,     40,      5,      0],
       [368762,     60,      7,      0],
       [299620,     10,      7,      0],
       [ 42704,     75,      8,      0],
       [238846,     15,      8,      0],
       [111500,     15,      4,      1],
       [202633,     45,     10,      0],
       [309419,     75,      8,      0],
       [187322,      5,      7,      0],
       [ 14253,     10,      9,      0],
       [205356,     28,      9,      0],
       [ 32736,     45,      9,      0],
       [380421,     30,      7,      0],
       [490918,     35,     17,      0],
       [271217,     10,      4,      1],
       [178242,     80,     17,      0],
       [178540,     70,      6,      0],
       [316184,     15,      5,      1],
       [408293,     35,      4,      0],
       [ 76604, 

13. Выведите процент "простых" рецептов в датасете

In [134]:
vsegoprost = np.sum(file12[:, 3])
vsego = len(file12)
print(f'Процент простых рецептов в датасете: {round((vsegoprost/vsego) * 100, 2)}%')

Процент простых рецептов в датасете: 9.55%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [137]:
file14 = file4.copy()
short_recipe = file14[file14[:,1] < 10]
midle_recipe = file14[(10 <= file4[:,1]) & (file4[:,1] < 20)]
long_recipe = file14[file4[:, 1] >= 20]
min_recipe = min(len(short_recipe), len(midle_recipe), len(long_recipe))
print(min_recipe)
itog_recipes = np.array([short_recipe[:min_recipe], midle_recipe[:min_recipe], long_recipe[:min_recipe]])
itog_recipes


7588


array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      0,      9],
        [370915,      5,      4]],

       [[ 94746,     10,      6],
        [ 33941,     18,      9],
        [446597,     15,      5],
        ...,
        [  9831,     15,      7],
        [335859,     12,     14],
        [256812,     10,      3]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]])